### ISSUE TITLE
Check that the default log system can use JSON and other "processable" formats

### ISSUE THREAD

**Issue by JJ** [cecimerelo/UnAlgoritmoFeliz#28]
https://github.com/cecimerelo/UnAlgoritmoFeliz/blob/6f6a44b76347665d0f68bac750c993d94802d8dd/src/brave_new_algorithm.jl#L21-L22

**Comment by cecimerelo** [comment]
For the future: Take a look at 

https://discourse.julialang.org/t/how-to-save-logging-output-to-a-log-file/14004/9

**Comment by cecimerelo** [comment]
Not needed, information will be stored in a Dataframe and then in a CSV.
